openapi: 3.0.0
info:
  title: House Keeping API
  version: 0.1.0-SNAPSHOT
  description: House Keeping API
  license:
    name: Apache 2.0
servers:
  - url: 'http://localhost:8080'
paths:
  /missions:
    get:
      summary: List Missions
      tags:
        - Mission
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionListResponse'
      operationId: get-missions
    delete:
      summary: Remove Missions
      operationId: delete-missions
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MissionRemoveRequest'
      description: ''
      tags:
        - Mission
    put:
      summary: Register Missions
      operationId: put-missions
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MissionRegisterRequest'
      tags:
        - Mission
    post:
      summary: New Mission
      operationId: post-missions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MissionNewRequest'
      tags:
        - Mission
components:
  schemas:
    MissionRegisterRequest:
      title: MissionRegisterRequest
      type: object
      x-examples:
        example-1:
          date: '2020-06-21'
          finished:
            - 1
            - 2
            - 3
      properties:
        date:
          type: string
          format: date
        finished:
          type: array
          items:
            type: integer
            format: int32
      x-tags:
        - Mission
    MissionListResponse:
      title: MissionListRequest
      type: array
      x-tags:
        - Mission
      items:
        $ref: '#/components/schemas/MissionResponse'
    MissionResponse:
      title: MissionResponse
      type: object
      x-examples:
        example-1:
          id: 1
          place: 洗面所
          lastDate: '2020-04-15'
          cycle: 14
      x-tags:
        - Mission
      properties:
        id:
          type: integer
          format: int32
        place:
          type: string
        lastDate:
          type: string
          format: date
        cycle:
          type: integer
          format: int32
    MissionRemoveRequest:
      title: MissionDeleteRequest
      type: object
      x-examples:
        example-1:
          remove:
            - 1
            - 2
      properties:
        remove:
          type: array
          items:
            type: integer
            format: int32
      x-tags:
        - Mission
    MissionNewRequest:
      title: MissionNewRequest
      type: object
      properties:
        place:
          type: string
        cycle:
          type: integer
          format: int32
